/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import static finalproject.FinalProject.retrieveClientData;
import static finalproject.FinalProject.retrieveFlightData;
import java.util.*;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Natsu
 */
public class ClientPage extends javax.swing.JFrame {

    Client client = new Client();
    List<Client> clientModel = retrieveClientData();
    ClientView clientView = new ClientView();
    ClientController clientController = new ClientController(clientModel, clientView);

    List<Flight> flightModel = retrieveFlightData();
    FlightView flightView = new FlightView();
    FlightController flightController = new FlightController(flightModel, flightView);
    Flight flight = new Flight();
    
    ResourceBundle res;

    public ClientPage() {
        initComponents();
        englishButton.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextField = new javax.swing.JTextArea();
        viewFlightBoardButton = new javax.swing.JButton();
        englishButton = new javax.swing.JButton();
        frenchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        destinationTextField = new javax.swing.JTextField();
        searchBDestinationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DurationTextField = new javax.swing.JTextField();
        searchBDurationButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        originTextField = new javax.swing.JTextField();
        searchBOriginButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayTextField.setColumns(20);
        displayTextField.setRows(5);
        displayTextField.setName(""); // NOI18N
        jScrollPane1.setViewportView(displayTextField);
        displayTextField.getAccessibleContext().setAccessibleName("displayTextField");

        viewFlightBoardButton.setText("View Flight Board");
        viewFlightBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightBoardButtonActionPerformed(evt);
            }
        });

        englishButton.setText("English");
        englishButton.setSelected(true);
        englishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishButtonActionPerformed(evt);
            }
        });

        frenchButton.setText("French");
        frenchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Search by Destination");

        destinationTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        searchBDestinationButton.setText("Search");
        searchBDestinationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBDestinationButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Search by Duration");

        DurationTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        searchBDurationButton1.setText("Search");
        searchBDurationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBDurationButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Search by Origin");

        originTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        searchBOriginButton2.setText("Search");
        searchBOriginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBOriginButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(englishButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frenchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBDurationButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBDestinationButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBOriginButton2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewFlightBoardButton)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(englishButton)
                            .addComponent(frenchButton))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBDestinationButton)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBDurationButton1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(originTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBOriginButton2)
                            .addComponent(jLabel3))
                        .addGap(123, 123, 123)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(viewFlightBoardButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        viewFlightBoardButton.getAccessibleContext().setAccessibleName("jViewFBoardButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewFlightBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightBoardButtonActionPerformed
        displayTextField.setText("");

        String str = "";

        str += res.getString("key4") + "\n";
        str += flightController.updateView(Flight.viewBoard());

        displayTextField.setText(str);
    }//GEN-LAST:event_viewFlightBoardButtonActionPerformed

    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishButtonActionPerformed
        displayTextField.setText("");
        Locale locale = new Locale("en", "CA");
        res = ResourceBundle.getBundle("finalproject/file", locale);
    }//GEN-LAST:event_englishButtonActionPerformed

    private void frenchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchButtonActionPerformed
        displayTextField.setText("");
        Locale locale = new Locale("fr", "CA");
        res = ResourceBundle.getBundle("finalproject/file", locale);
    }//GEN-LAST:event_frenchButtonActionPerformed

    private void searchBDestinationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBDestinationButtonActionPerformed
        displayTextField.setText("");

        List<String> list = new ArrayList<>();

        String str = "";

        str += res.getString("key10") + "\n";

        client.searchFlightByDest(destinationTextField.getText()).forEach(dest
                -> {
            list.add(dest.toString());
        });

        str += list;

        displayTextField.setText(str);
        viewFlightBoardButton.setEnabled(true);
        destinationTextField.setText("");
        DurationTextField.setText("");
        originTextField.setText("");

    }//GEN-LAST:event_searchBDestinationButtonActionPerformed

    private void searchBDurationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBDurationButton1ActionPerformed
       displayTextField.setText("");

        List<String> list = new ArrayList<>();

        String str = "";

        str += res.getString("key11") + "\n";

        client.searchFlightByDuration(Integer.parseInt(DurationTextField.getText())).forEach(dur
                -> {
            list.add(dur.toString());
        });

        str += list;

        displayTextField.setText(str);
        viewFlightBoardButton.setEnabled(true);
        destinationTextField.setText("");
        DurationTextField.setText("");
        originTextField.setText("");
    }//GEN-LAST:event_searchBDurationButton1ActionPerformed

    private void searchBOriginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBOriginButton2ActionPerformed
         displayTextField.setText("");

        List<String> list = new ArrayList<>();

        String str = "";

        str += res.getString("key12") + "\n";

        client.searchFlighByOrigin(originTextField.getText()).forEach(ori
                -> {
            list.add(ori.toString());
        });

        str += list;

        displayTextField.setText(str);
        viewFlightBoardButton.setEnabled(true);
        destinationTextField.setText("");
        DurationTextField.setText("");
        originTextField.setText("");
    }//GEN-LAST:event_searchBOriginButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPage().setVisible(true);

                List<Flight> flightModel = retrieveFlightData();
                FlightView flightView = new FlightView();
                FlightController flightController = new FlightController(flightModel, flightView);
                Flight flight = new Flight();

                List<Client> clientModel = retrieveClientData();
                ClientView clientView = new ClientView();
                ClientController clientController = new ClientController(clientModel, clientView);
                Client client = new Client();

                String SQL_CREATE_TABLE_FLIGHTS = "CREATE TABLE FLIGHTS "
                        + "(FLIGHTN TEXT PRIMARY KEY      NOT NULL,"
                        + " NAME                     TEXT NOT NULL,"
                        + " ORIGIN                   TEXT NOT NULL,"
                        + " DEST                     TEXT NOT NULL,"
                        + " DURATION                  INT NOT NULL,"
                        + " SEATS                     INT NOT NULL,"
                        + " AVAILABLE                 INT NOT NULL,"
                        + " AMOUNT                    INT NOT NULL)";

                String SQL_CREATE_TABLE_CLIENTS = "CREATE TABLE CLIENTS "
                        + "(PASSNUM INT PRIMARY KEY       NOT NULL,"
                        + " FULLNAME                 TEXT NOT NULL,"
                        + " CONTACT                   INT NOT NULL)";

                String SQL_CREATE_TABLE_RESERVEDFLIGHTS = "CREATE TABLE RESERVEDFLIGHTS "
                        + "(TICKETN INT PRIMARY KEY       ,"
                        + " FLIGHTN                  TEXT NOT NULL,"
                        + " PASSNUM                   INT NOT NULL,"
                        + " FLNAME                   TEXT NOT NULL,"
                        + " ISSUEDATE                DATE NOT NULL,"
                        + " CONTACT                   INT NOT NULL,"
                        + " AMOUNT                    INT NOT NULL,"
                        + " CONSTRAINT FK_RESERVE_FLIGHN FOREIGN KEY(FLIGHTN)"
                        + " REFERENCES FLIGHTS(FLIGHTN),"
                        + " CONSTRAINT FK_RESERVE_PASSNUM FOREIGN KEY(PASSNUM)"
                        + " REFERENCES CLIENTS(PASSNUM))";

                flightController.createFlightsTable(SQL_CREATE_TABLE_FLIGHTS);
                //System.out.println("\nTABLE RESERVEDFLIGHTS FLIGHTS");
                //System.out.println("\n" + res.getString("key1"));
                clientController.createClientsTable(SQL_CREATE_TABLE_CLIENTS);
                //System.out.println("\nTABLE RESERVEDFLIGHTS CLIENTS");
                //System.out.println("\n" + res.getString("key2"));
                flightController.createReservedFlightsTable(SQL_CREATE_TABLE_RESERVEDFLIGHTS);
                //System.out.println("\nTABLE RESERVEDFLIGHTS CREATED");
                // System.out.println("\n" + res.getString("key3"));

                flightModel.forEach((fl) -> {
                    flight.addFlight(fl);
                });

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DurationTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTextArea displayTextField;
    private javax.swing.JButton englishButton;
    private javax.swing.JButton frenchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField originTextField;
    private javax.swing.JButton searchBDestinationButton;
    private javax.swing.JButton searchBDurationButton1;
    private javax.swing.JButton searchBOriginButton2;
    private javax.swing.JButton viewFlightBoardButton;
    // End of variables declaration//GEN-END:variables
}
